name: Docker Auto Deploy VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t hello-world .

    - name: Tagging Docker Image
      run: docker tag hello-world kavita346/hello-world

    - name: Logging into docker hub
      run: docker login -u kavita346 -p ${{ secrets.docker_password}}
    
