name: Docker Auto Deploy VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: |
    - name: Checkout code
      uses: actions/checkout@v2

    -name : Build & Push Image
      run: docker build -t hello-world .
      run: docker tag hello-world "${{ secrets.DOCKER_USERNAME_SAI40 }}"/hello-world
      run: echo "${{ secrets.DOCKER_PASSWORD_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME_SAI40 }}" --password-stdin
      run: docker push "${{ secrets.DOCKER_USERNAME_SAI40 }}"/hello-world
